# Generated by Django 6.0.3 on 2026-03-27 15:54

import core.utils.upload_handlers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimage',
            name='image',
            field=models.ImageField(upload_to=core.utils.upload_handlers.custom_upload_to, verbose_name='Изображение'),
        ),
    ]
