# Generated by Django 6.0.3 on 2026-03-27 18:27

import core.utils.upload_handlers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_workimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=core.utils.upload_handlers.custom_upload_to, verbose_name='Видео')),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.work')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['order'],
            },
        ),
    ]
