# Generated by Django 6.0.3 on 2026-03-27 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_admin_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендует администрация'),
        ),
        migrations.AddField(
            model_name='work',
            name='recommended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_works', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_time', models.FloatField(verbose_name='Время кадра (сек)')),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to='works/frames/', verbose_name='Кадр')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='core.workvideo')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='core.work')),
            ],
            options={
                'verbose_name': 'Кадр видео',
                'verbose_name_plural': 'Кадры видео',
                'ordering': ['order'],
            },
        ),
    ]
