# Generated by Django 6.0.3 on 2026-03-27 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_work_is_admin_recommended_work_recommended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workframe',
            name='frame_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Время кадра (сек)'),
        ),
        migrations.AlterField(
            model_name='workframe',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='core.workvideo'),
        ),
    ]
