# Generated by Django 6.0.3 on 2026-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_workframe_frame_time_alter_workframe_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWorksSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('refresh_interval', models.PositiveIntegerField(default=10, help_text='Как часто обновлять счетчик новых работ (в секундах)', verbose_name='Интервал обновления (сек)')),
                ('max_new_works_display', models.PositiveIntegerField(default=50, help_text='Максимальное количество новых работ для отображения', verbose_name='Макс. новых работ')),
                ('max_comments_display', models.PositiveIntegerField(default=20, help_text='Максимальное количество комментариев для отображения', verbose_name='Макс. комментариев')),
                ('show_in_header', models.BooleanField(default=True, verbose_name='Показывать в шапке')),
                ('show_in_notifications', models.BooleanField(default=True, verbose_name='Показывать в уведомлениях')),
                ('badge_color', models.CharField(default='#ef4444', help_text='Hex цвет для бейджа уведомлений', max_length=20, verbose_name='Цвет бейджа')),
                ('track_categories', models.BooleanField(default=True, verbose_name='Отслеживать категории')),
                ('track_comments', models.BooleanField(default=True, verbose_name='Отслеживать комментарии')),
                ('comment_lookback_hours', models.PositiveIntegerField(default=24, help_text='За сколько часов показывать новые комментарии', verbose_name='Период комментариев (часы)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки новых работ',
                'verbose_name_plural': 'Настройки новых работ и комментариев',
            },
        ),
    ]
