# Generated by Django 6.0.3 on 2026-03-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_ban_reason_profile_banned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_senior_moderator',
            field=models.BooleanField(default=False, verbose_name='Старший модератор'),
        ),
    ]
