# Generated by Django 6.0.3 on 2026-03-28 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_moderator_profile_is_senior_moderator'),
        ('core', '0005_alter_workframe_frame_time_alter_workframe_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Просмотр категории',
                'verbose_name_plural': 'Просмотры категорий',
                'indexes': [models.Index(fields=['user', 'category'], name='accounts_us_user_id_6f54dd_idx'), models.Index(fields=['user', '-last_viewed_at'], name='accounts_us_user_id_07bd6e_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
