# Generated by Django 6.0.3 on 2026-03-28 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usercategoryview'),
        ('core', '0006_newworkssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notify_new_works', models.BooleanField(default=True, verbose_name='Новые работы')),
                ('notify_new_comments', models.BooleanField(default=True, verbose_name='Новые комментарии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Любимая категория',
                'verbose_name_plural': 'Любимые категории',
                'indexes': [models.Index(fields=['user', 'category'], name='accounts_us_user_id_fddce0_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
