# Generated by Django 6.0.3 on 2026-03-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_block_fields_to_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Имя папки с иконками (например: default, business, minimal)', unique=True, verbose_name='Слаг')),
                ('is_active', models.BooleanField(default=False, help_text='Только один набор может быть активным', verbose_name='Активный набор')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Набор иконок',
                'verbose_name_plural': 'Наборы иконок',
                'ordering': ['name'],
            },
        ),
    ]
