# Generated by Django 6.0.3 on 2026-04-04 13:26

import core.utils.upload_handlers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_iconset_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=core.utils.upload_handlers.custom_upload_to, verbose_name='Аудио')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='core.work')),
            ],
            options={
                'verbose_name': 'Аудио',
                'verbose_name_plural': 'Аудио',
                'ordering': ['order'],
            },
        ),
    ]
