# Generated by Django 6.0.3 on 2026-04-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_projectcomment_projectcommentlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bg_color',
            field=models.CharField(default='#FFFFFF', max_length=20, verbose_name='Цвет фона'),
        ),
        migrations.AddField(
            model_name='project',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/bg/', verbose_name='Фоновое изображение'),
        ),
    ]
