# Generated by Django 6.0.3 on 2026-03-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('messages_count', models.PositiveIntegerField(default=0)),
                ('members_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderators', models.ManyToManyField(blank=True, related_name='moderated_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
                'ordering': ['-messages_count'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст сообщения')),
                ('has_image', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/images/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='chat.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бан в канале',
                'verbose_name_plural': 'Баны в каналах',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Модератор')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Заглушен')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник канала',
                'verbose_name_plural': 'Участники каналов',
            },
        ),
        migrations.CreateModel(
            name='MessageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк сообщения',
                'verbose_name_plural': 'Лайки сообщений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['slug'], name='chat_chann_slug_39c2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['is_public', 'is_active'], name='chat_chann_is_publi_4c1f85_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', '-created_at'], name='chat_messa_chann_9c300f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', '-created_at'], name='chat_messa_user_id_8a8d02_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted'], name='chat_messa_is_del_49f00d_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmember',
            index=models.Index(fields=['user', 'is_moderator'], name='chat_chann_user_id_0c9f33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmember',
            unique_together={('channel', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='channelban',
            unique_together={('channel', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='messagelike',
            unique_together={('message', 'user')},
        ),
    ]
