# Generated by Django 6.0.3 on 2026-03-26 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_channel_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_users', to='chat.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_online_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Онлайн пользователь в канале',
                'verbose_name_plural': 'Онлайн пользователи в каналах',
                'indexes': [models.Index(fields=['channel', 'last_activity'], name='chat_channe_channel_271fa5_idx')],
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
