# Generated by Django 6.0.3 on 2026-03-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_add_channel_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип файла'),
        ),
        migrations.AddField(
            model_name='message',
            name='has_file',
            field=models.BooleanField(default=False),
        ),
    ]
