# Generated by Django 6.0.3 on 2026-03-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userfavoritecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_works_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
