# Generated by Django 6.0.3 on 2026-04-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_blocked_works_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Показывать email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tools',
            field=models.TextField(blank=True, help_text='Программы, в которых работает пользователь (через запятую)', verbose_name='Программы'),
        ),
    ]
