# Generated by Django 6.0.3 on 2026-03-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channel',
            new_name='chat_channe_slug_891a51_idx',
            old_name='chat_chann_slug_39c2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='channel',
            new_name='chat_channe_is_publ_974e7b_idx',
            old_name='chat_chann_is_publi_4c1f85_idx',
        ),
        migrations.RenameIndex(
            model_name='channelmember',
            new_name='chat_channe_user_id_3d59fd_idx',
            old_name='chat_chann_user_id_0c9f33_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_channel_fb213f_idx',
            old_name='chat_messa_chann_9c300f_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_user_id_ce6f7a_idx',
            old_name='chat_messa_user_id_8a8d02_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_is_dele_543a03_idx',
            old_name='chat_messa_is_del_49f00d_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
    ]
