# Generated by Django 6.0.3 on 2026-03-26 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_reply_to_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChannelRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message_id', models.PositiveIntegerField(default=0, verbose_name='ID последнего прочитанного сообщения')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='Количество прочитанных сообщений')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_read_status', to='chat.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_read_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статус прочтения канала',
                'verbose_name_plural': 'Статусы прочтения каналов',
                'indexes': [models.Index(fields=['user', 'channel'], name='chat_userch_user_id_3169bc_idx')],
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
