# Generated by Django 6.0.3 on 2026-03-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userchannelread'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/channel_images/', verbose_name='Изображение канала'),
        ),
    ]
