# Generated by Django 6.0.3 on 2026-03-27 15:54

import core.utils.upload_handlers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_add_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.upload_handlers.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_handlers.custom_upload_to),
        ),
    ]
